In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
house_prices = pd.read_csv("train.csv")

In [80]:
house_prices

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,2-STORY 1946 & NEWER,RL,65.0,8450,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,1-STORY 1946 & NEWER ALL STYLES,RL,80.0,9600,Pave,No alley access,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,2-STORY 1946 & NEWER,RL,68.0,11250,Pave,No alley access,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,2-STORY 1945 & OLDER,RL,60.0,9550,Pave,No alley access,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,2-STORY 1946 & NEWER,RL,84.0,14260,Pave,No alley access,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,2-STORY 1946 & NEWER,RL,62.0,7917,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1-STORY 1946 & NEWER ALL STYLES,RL,85.0,13175,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,2-STORY 1945 & OLDER,RL,66.0,9042,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1-STORY 1946 & NEWER ALL STYLES,RL,68.0,9717,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1-STORY 1946 & NEWER ALL STYLES,RL,75.0,9937,Pave,No alley access,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
house_prices.drop("Id" , axis=1, inplace=True)

In [70]:
house_prices.select_dtypes("object").columns

Index(['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [15]:
house_prices["MSSubClass"]= house_prices["MSSubClass"].map({20:	"1-STORY 1946 & NEWER ALL STYLES",
        30:	"1-STORY 1945 & OLDER",
        40:	"1-STORY W/FINISHED ATTIC ALL AGES",
        45:	"1-1/2 STORY - UNFINISHED ALL AGES",
        50:	"1-1/2 STORY FINISHED ALL AGES",
        60:	"2-STORY 1946 & NEWER",
        70:	"2-STORY 1945 & OLDER",
        75:	"2-1/2 STORY ALL AGES",
        80:	"SPLIT OR MULTI-LEVEL",
        85:	"SPLIT FOYER",
        90:	"DUPLEX - ALL STYLES AND AGES",
       120:	"1-STORY PUD (Planned Unit Development) - 1946 & NEWER",
       150:	"1-1/2 STORY PUD - ALL AGES",
       160:	"2-STORY PUD - 1946 & NEWER",
       180:	"PUD - MULTILEVEL - INCL SPLIT LEV/FOYER",
       190:	"2 FAMILY CONVERSION - ALL STYLES AND AGES"})

In [69]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage      259
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      37
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1452
Fence           1178
MiscFeature     1405
dtype: int64

In [ ]:
house_prices["Alley"]=house_prices["Alley"].map({"Grvl":	"Gravel",
       "Pave":	"Paved",
       np.NaN: 	"No alley access"})

In [155]:

house_prices.drop(house_prices[house_prices["MasVnrType"].isnull()].index , inplace=True)

In [156]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage    257
dtype: int64

In [64]:
house_prices[house_prices["BsmtExposure"].isnull()!=house_prices["BsmtCond"].isnull()]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
948,2-STORY 1946 & NEWER,RL,65.0,14006,Pave,No alley access,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2006,WD,Normal,192500

In [68]:
house_prices=house_prices.drop(948)

In [74]:
house_prices["BsmtQual"]=house_prices["BsmtQual"].map({"Ex":	"Excellent (100+ inches)",	
       "Gd":	"Good (90-99 inches)" , 
       "TA":	"Typical (80-89 inches)",
       "Fa":	"Fair (70-79 inches)" , 
       "Po":	"Poor (<70 inches)" , 
       np.NaN:	"No Basement"})
house_prices["BsmtCond"]=house_prices["BsmtCond"].map({"Ex":	"Excellent (100+ inches)",	
       "Gd":	"Good (90-99 inches)" , 
       "TA":	"Typical (80-89 inches)" ,
       "Fa":	"Fair (70-79 inches)" , 
       "Po":	"Poor (<70 inches)" , 
       np.NaN:	"No Basement"})

In [77]:
house_prices["BsmtExposure"]=house_prices["BsmtExposure"].map({"Gd":	"Good Exposure",
       "Av":	"Average Exposure (split levels or foyers typically score average or above",
       "Mn":	"Mimimum Exposure",
       "No":	"No Exposure",
       np.NaN:	"No Basement"})

In [78]:
house_prices["BsmtFinType1"]=house_prices["BsmtFinType1"].map({"GLQ":	"Good Living Quarters",
       "ALQ":	"Average Living Quarters",
       "BLQ":	"Below Average Living Quarters"	,
       "Rec":	"Average Rec Room",
       "LwQ":	"Low Quality",
       "Unf":	"Unfinshed",
       np.NaN:	"No Basement"})
house_prices["BsmtFinType2"]=house_prices["BsmtFinType2"].map({"GLQ":	"Good Living Quarters",
       "ALQ":	"Average Living Quarters",
       "BLQ":	"Below Average Living Quarters"	,
       "Rec":	"Average Rec Room",
       "LwQ":	"Low Quality",
       "Unf":	"Unfinshed",
       np.NaN:	"No Basement"})

In [79]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage      259
MasVnrType         8
MasVnrArea         8
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1452
Fence           1178
MiscFeature     1405
dtype: int64

In [153]:
house_prices.drop(house_prices[house_prices["Electrical"].isnull()].index , inplace=True)

In [87]:
house_prices["FireplaceQu"]=house_prices["FireplaceQu"].map({"Ex":	"Excellent - Exceptional Masonry Fireplace",
       "Gd":	"Good - Masonry Fireplace in main level",
       "TA":	"Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement",
       "Fa":	"Fair - Prefabricated Fireplace in basement",
       "Po":	"Poor - Ben Franklin Stove",
       np.NaN:  "No Fireplace"})

In [154]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage    259
MasVnrType       8
MasVnrArea       8
dtype: int64

In [126]:
def garagena(x):
    if x is np.NaN:
        return "No Garage"
    else:
        return x

In [128]:
garagena(None)

0

In [116]:
for name in ["GarageType", "GarageFinish", "GarageQual", "GarageCond"]:
    house_prices[name]=house_prices[name].apply(lambda x : garagena(x))

In [130]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage     259
MasVnrType        8
MasVnrArea        8
Electrical        1
GarageYrBlt      81
PoolQC         1452
Fence          1178
MiscFeature    1405
dtype: int64

In [131]:
house_prices.loc[house_prices["GarageYrBlt"].isnull() , "GarageYrBlt"]=0

In [132]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage     259
MasVnrType        8
MasVnrArea        8
Electrical        1
PoolQC         1452
Fence          1178
MiscFeature    1405
dtype: int64

In [136]:
def poolna(x):
    if x is np.NaN:
        return "No Pool"
    else:
        return x

In [134]:
house_prices[house_prices["PoolQC"].isnull()]["PoolArea"].value_counts()

0    1452
Name: PoolArea, dtype: int64

In [138]:
house_prices["PoolQC"]=house_prices["PoolQC"].apply(lambda x: poolna(x))

In [139]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage     259
MasVnrType        8
MasVnrArea        8
Electrical        1
Fence          1178
MiscFeature    1405
dtype: int64

In [140]:
def fencena(x):
    if x is np.NaN:
        return "No Fence"
    else:
        return x

In [146]:
house_prices["Fence"]=house_prices["Fence"].apply(lambda x: fencena(x))

In [143]:
def genericna(x):
    if x is np.NaN:
        return "No"
    else:
        return x

In [144]:
house_prices["MiscFeature"]=house_prices["MiscFeature"].apply(lambda x: genericna(x))

In [157]:
house_prices.isna().sum()[house_prices.isna().sum()>0]

LotFrontage    257
dtype: int64

In [158]:
house_prices.corr()["LotFrontage"]

LotFrontage      1.000000
LotArea          0.425680
OverallQual      0.250342
OverallCond     -0.058860
YearBuilt        0.123258
YearRemodAdd     0.088574
MasVnrArea       0.193587
BsmtFinSF1       0.234934
BsmtFinSF2       0.050238
BsmtUnfSF        0.130497
TotalBsmtSF      0.391330
1stFlrSF         0.456369
2ndFlrSF         0.081370
LowQualFinSF     0.038657
GrLivArea        0.402360
BsmtFullBath     0.101847
BsmtHalfBath    -0.007079
FullBath         0.196905
HalfBath         0.054466
BedroomAbvGr     0.262974
KitchenAbvGr    -0.005918
TotRmsAbvGrd     0.351450
Fireplaces       0.266542
GarageYrBlt      0.105284
GarageCars       0.284878
GarageArea       0.344734
WoodDeckSF       0.087273
OpenPorchSF      0.149889
EnclosedPorch    0.011006
3SsnPorch        0.070278
ScreenPorch      0.041691
PoolArea         0.206707
MiscVal          0.003476
MoSold           0.010274
YrSold           0.008197
SalePrice        0.350335
Name: LotFrontage, dtype: float64

In [159]:
dummies=pd.get_dummies(house_prices[["MSSubClass", 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition']] , drop_first=True)

In [160]:
dummies

,MSSubClass_1-1/2 STORY FINISHED ALL AGES,MSSubClass_1-STORY 1945 & OLDER,MSSubClass_1-STORY 1946 & NEWER ALL STYLES,MSSubClass_1-STORY PUD (Planned Unit Development) - 1946 & NEWER,MSSubClass_1-STORY W/FINISHED ATTIC ALL AGES,MSSubClass_2 FAMILY CONVERSION - ALL STYLES AND AGES,MSSubClass_2-1/2 STORY ALL AGES,MSSubClass_2-STORY 1945 & OLDER,MSSubClass_2-STORY 1946 & NEWER,MSSubClass_2-STORY PUD - 1946 & NEWER,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1456,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1457,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
1458,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1459,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [161]:
price_with_dummies= pd.concat([house_prices.drop(["MSSubClass", 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'] , axis=1) , dummies] , axis=1)

In [19]:
price_with_dummies

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,65.0,8450,7,5,2003,2003,196.0,706,0,150,...,0,0,0,0,1,0,0,0,1,0
1,80.0,9600,6,8,1976,1976,0.0,978,0,284,...,0,0,0,0,1,0,0,0,1,0
2,68.0,11250,7,5,2001,2002,162.0,486,0,434,...,0,0,0,0,1,0,0,0,1,0
3,60.0,9550,7,5,1915,1970,0.0,216,0,540,...,0,0,0,0,1,0,0,0,0,0
4,84.0,14260,8,5,2000,2000,350.0,655,0,490,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,6,5,1999,2000,0.0,0,0,953,...,0,0,0,0,1,0,0,0,1,0
1456,85.0,13175,6,6,1978,1988,119.0,790,163,589,...,0,0,0,0,1,0,0,0,1,0
1457,66.0,9042,7,9,1941,2006,0.0,275,0,877,...,0,0,0,0,1,0,0,0,1,0
1458,68.0,9717,5,6,1950,1996,0.0,49,1029,0,...,0,0,0,0,1,0,0,0,1,0
1459,75.0,9937,5,6,1965,1965,0.0,830,290,136,...,0,0,0,0,1,0,0,0,1,0

In [163]:
price_with_dummies.corr()["LotFrontage"]

LotFrontage              1.000000
LotArea                  0.425680
OverallQual              0.250342
OverallCond             -0.058860
YearBuilt                0.123258
                           ...
SaleCondition_AdjLand   -0.037075
SaleCondition_Alloca    -0.019796
SaleCondition_Family     0.016817
SaleCondition_Normal    -0.074913
SaleCondition_Partial    0.125483
Name: LotFrontage, Length: 273, dtype: float64